name: Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/firmware.yml"
  pull_request:
    paths:
      - "firmware/**"
      - ".github/workflows/firmware.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install platformio
      - run: cp include/Secrets.example.h include/Secrets.h
        working-directory: firmware
      - run: pio run
        working-directory: firmware
